/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransacoesRouteImport } from './routes/_app.transacoes'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppOrcamentoRouteImport } from './routes/_app.orcamento'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContasAPagarRouteImport } from './routes/_app.contas-a-pagar'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOrcamentoRoute = AppOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContasAPagarRoute = AppContasAPagarRouteImport.update({
  id: '/contas-a-pagar',
  path: '/contas-a-pagar',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AppCategoriasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contas-a-pagar': typeof AppContasAPagarRoute
  '/dashboard': typeof AppDashboardRoute
  '/metas': typeof AppMetasRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AppCategoriasRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contas-a-pagar': typeof AppContasAPagarRoute
  '/dashboard': typeof AppDashboardRoute
  '/metas': typeof AppMetasRoute
  '/orcamento': typeof AppOrcamentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contas-a-pagar': typeof AppContasAPagarRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/orcamento': typeof AppOrcamentoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/transacoes': typeof AppTransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/dashboard'
    | '/metas'
    | '/orcamento'
    | '/relatorios'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categorias'
    | '/configuracoes'
    | '/contas-a-pagar'
    | '/dashboard'
    | '/metas'
    | '/orcamento'
    | '/relatorios'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/categorias'
    | '/_app/configuracoes'
    | '/_app/contas-a-pagar'
    | '/_app/dashboard'
    | '/_app/metas'
    | '/_app/orcamento'
    | '/_app/relatorios'
    | '/_app/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transacoes': {
      id: '/_app/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orcamento': {
      id: '/_app/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AppOrcamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contas-a-pagar': {
      id: '/_app/contas-a-pagar'
      path: '/contas-a-pagar'
      fullPath: '/contas-a-pagar'
      preLoaderRoute: typeof AppContasAPagarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContasAPagarRoute: typeof AppContasAPagarRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMetasRoute: typeof AppMetasRoute
  AppOrcamentoRoute: typeof AppOrcamentoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContasAPagarRoute: AppContasAPagarRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMetasRoute: AppMetasRoute,
  AppOrcamentoRoute: AppOrcamentoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTransacoesRoute: AppTransacoesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
